import {test} from 'node:test';
import assert from 'node:assert/strict';
test('Persist, schedule, deliver once, reject past, delete and restore alarms',async()=>{
  let store={},alarms=new Map(),sent=[],listeners={};
  const event=name=>({addListener(fn){listeners[name]=fn;}});
  globalThis.chrome={runtime:{id:'test',onMessage:event('message'),onInstalled:event('install'),onStartup:event('startup'),getURL:p=>p},storage:{onChanged:event('storage'),local:{async get(key){return key?{[key]:store[key]}:{...store};},async set(o){Object.assign(store,o);},async remove(key){delete store[key];}}},alarms:{onAlarm:event('alarm'),async get(key){return alarms.get(key);},async create(key,value){alarms.set(key,value);},async clear(key){alarms.delete(key);}},notifications:{onClicked:event('click'),async create(id,value){sent.push({id,...value});},async clear(){}},sidePanel:{async setPanelBehavior(){}},tabs:{async create(){}}};
  await import('../background.js');
  const send=message=>new Promise(resolve=>listeners.message(message,{id:'test'},resolve));
  let response=await send({type:'add',title:'آزمون یادآور',date:'2099-01-01',time:'09:00'});
  assert.equal(response.ok,true);const r=response.reminder;
  assert.ok(store[`reminder:${r.id}`]);assert.ok(alarms.has(`rooz:${r.id}`));
  await send({type:'seen',ids:[r.id]});assert.equal(store[`reminder:${r.id}`].seenAt,undefined);
  alarms.clear();await send({type:'sync'});assert.ok(alarms.has(`rooz:${r.id}`));
  store[`reminder:${r.id}`].when=Date.now()-1000;
  await send({type:'sync'});assert.equal(sent.length,1);assert.ok(store[`reminder:${r.id}`].firedAt);
  await send({type:'seen',ids:[r.id]});assert.ok(store[`reminder:${r.id}`].seenAt);
  await send({type:'sync'});assert.equal(sent.length,1);
  response=await send({type:'add',title:'past',date:'2020-01-01',time:'09:00'});assert.equal(response.ok,false);
  await send({type:'delete',id:r.id});assert.equal(store[`reminder:${r.id}`],undefined);assert.equal(alarms.size,0);
  const saved=await send({type:'save-item',date:'2099-01-01',text:'متن یکپارچه',remind:false});assert.equal(saved.ok,true);
  const original=store[saved.key];
  const enabled=await send({type:'save-item',key:saved.key,text:'متن یکپارچه',remind:true,time:'10:00'});assert.equal(enabled.ok,true);assert.equal(store[saved.key],undefined);assert.equal(store[enabled.key].createdAt,original.createdAt);assert.equal(alarms.size,1);
  const disabled=await send({type:'save-item',key:enabled.key,text:'ویرایش متن',remind:false});assert.equal(disabled.ok,true);assert.equal(store[enabled.key],undefined);assert.equal(store[disabled.key].text,'ویرایش متن');assert.equal(store[disabled.key].createdAt,original.createdAt);assert.equal(alarms.size,0);
  const bad=await send({type:'save-item',date:'2020-01-01',text:'زمان گذشته',remind:true,time:'09:00'});assert.equal(bad.ok,false);
  assert.equal((await send({type:'save-series',date:'2099-01-01',text:'هر روز',time:'09:00',remind:true,mode:'daily',end:null,days:[]})).ok,true);
  const seriesKey=Object.keys(store).find(k=>k.startsWith('series:')),seriesId=store[seriesKey].id;
  assert.equal(alarms.size,1);
  await send({type:'delete-series',seriesId,scope:'one',date:'2099-01-01'});assert.equal(store[seriesKey].nextDate,'2099-01-02');
  await send({type:'save-series',seriesId,scope:'one',date:'2099-01-02',text:'فقط یک روز',remind:false,time:'09:00'});assert.equal(store[seriesKey].nextDate,'2099-01-03');
  await send({type:'save-series',seriesId,scope:'all',text:'همه',remind:true,time:'10:00',mode:'weekly',days:[0,2],end:'2099-02-01'});assert.equal(store[seriesKey].text,'همه');assert.deepEqual(store[seriesKey].exceptions,{});
  await send({type:'delete-series',seriesId,scope:'all'});assert.equal(store[seriesKey],undefined);assert.equal(alarms.size,0);
});
