import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const profile=await mkdtemp(path.join(tmpdir(),'rooz-test-'));
let context;
try{
  context=await chromium.launchPersistentContext(profile,{channel:'chromium',headless:true,args:[`--disable-extensions-except=${root}`,`--load-extension=${root}`],viewport:{width:390,height:920}});
  let worker=context.serviceWorkers()[0];if(!worker)worker=await context.waitForEvent('serviceworker');
  const id=new URL(worker.url()).host,page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`chrome-extension://${id}/sidepanel.html`);
  await page.locator('#calendar .day').first().waitFor();await page.evaluate(()=>document.fonts.ready);
  await page.waitForFunction(()=>document.querySelector('#today-weekday').textContent.length>0);
  assert.equal(await page.locator('#calendar .day').count(),7);
  console.log(await page.evaluate(async()=>{await document.fonts.load('14px Vazirmatn');return [...document.fonts].map(f=>({family:f.family,status:f.status}));}));
  assert.equal(await page.evaluate(()=>document.fonts.check('14px Vazirmatn')),true);
  await page.locator('#week-toggle').click();
  assert.ok(await page.locator('#calendar .day').count()>=28);
  await page.locator('#month-title').click();
  assert.equal(await page.locator('#jump-months button').count(),12);
  await page.locator('#jump-year').selectOption('1500');
  await page.locator('#jump-months').getByRole('button',{name:'آذر',exact:true}).click();
  assert.equal(await page.locator('#month-title').textContent(),'آذر ۱۵۰۰');
  assert.match(await page.locator('#selected-title').textContent(),/۱ آذر ۱۵۰۰/);
  assert.equal(await page.locator('#month-picker').isVisible(),false);
  await page.locator('#remind-toggle').check();await page.locator('#note').fill('یادآور آذر');await page.locator('#note-form button[type=submit]').click();await page.locator('.saved-note[data-kind=reminder]').waitFor();
  const jumpReminder=await worker.evaluate(async()=>Object.entries(await chrome.storage.local.get(null)).find(([key])=>key.startsWith('reminder:'))[1]);
  assert.equal(new Intl.DateTimeFormat('en-u-ca-persian',{timeZone:'Asia/Tehran',year:'numeric',month:'numeric',day:'numeric'}).format(new Date(jumpReminder.when)),'9/1/1500 AP');
  await page.locator('.saved-note[data-kind=reminder]').getByRole('button',{name:'ویرایش یادداشت یادآور آذر',exact:true}).click();
  assert.equal(await page.locator('#remind-toggle').isChecked(),true);
  assert.equal(await page.locator('#reminder-hour option').count(),24);
  assert.equal(await page.locator('#reminder-minute option').count(),60);
  await page.locator('#reminder-hour').selectOption('23');await page.locator('#reminder-minute').selectOption('59');
  assert.equal(await page.locator('#reminder-time').inputValue(),'23:59');
  await page.locator('#remind-toggle').uncheck();await page.locator('#note-form button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('.saved-note[data-kind=note]')&&!document.querySelector('.saved-note[data-kind=reminder]'));
  assert.equal((await worker.evaluate(()=>chrome.alarms.getAll())).length,0);
  await page.locator('.saved-note[data-kind=note]').getByRole('button',{name:'ویرایش یادداشت یادآور آذر',exact:true}).click();
  await page.locator('#remind-toggle').check();await page.locator('#note-form button[type=submit]').click();await page.locator('.saved-note[data-kind=reminder]').waitFor();
  assert.equal(await page.locator('.saved-note').count(),1);
  await page.locator('.saved-note[data-kind=reminder] .delete-note').click();await page.waitForFunction(()=>!document.querySelector('.saved-note[data-kind=reminder]'));
  await page.locator('#month-title').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#month-picker').isVisible(),false);
  await page.locator('#today').click();
  await page.locator('#note').fill('یادداشت آزمایشی — <script>alert(1)</script>');
  await page.getByRole('button',{name:'ثبت',exact:true}).click();
  await page.getByText('ذخیره شد',{exact:true}).waitFor();await page.reload();
  await page.locator('.saved-note').waitFor();
  assert.match(await page.locator('.saved-note .created-time').textContent(),/^ثبت [۰-۹]{2}:[۰-۹]{2}$/);
  const firstCreated=await page.locator('.saved-note .created-time').getAttribute('datetime');
  assert.ok(Number.isFinite(Date.parse(firstCreated)));
  assert.match(await page.locator('#day-notes').textContent(),/<script>alert\(1\)<\/script>/);
  await page.locator('#note').fill('یادداشت دوم');await page.locator('#note-form button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelectorAll('.saved-note').length===2);
  await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.saved-note').length===2);
  const legacyKey=await worker.evaluate(async()=>{
    const all=await chrome.storage.local.get(null),date=Object.entries(all).find(([key])=>key.startsWith('noteitem:'))[1].date,key=`note:${date}`;
    await chrome.storage.local.set({[key]:'یادداشت نسخه قبلی'});return key;
  });
  await page.waitForFunction(()=>document.querySelectorAll('.saved-note').length===3);
  assert.equal(await page.locator('.saved-note .created-time').count(),2);
  const secondCreated=await page.locator('.saved-note').filter({hasText:'یادداشت دوم'}).locator('.created-time').getAttribute('datetime');
  await page.getByRole('button',{name:'ویرایش یادداشت یادداشت دوم',exact:true}).click();
  await page.locator('#note').fill('یادداشت دوم ویرایش شده');await page.locator('#note-form button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('#day-notes').textContent.includes('ویرایش شده'));
  assert.equal(await page.locator('.saved-note').count(),3);
  assert.equal(await page.locator('.saved-note').filter({hasText:'ویرایش شده'}).locator('.created-time').getAttribute('datetime'),secondCreated);
  await page.getByRole('button',{name:'حذف یادداشت یادداشت نسخه قبلی',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.saved-note').length===2);
  assert.equal((await worker.evaluate(key=>chrome.storage.local.get(key),legacyKey))[legacyKey],undefined);
  await page.locator('.saved-note').filter({hasText:'آزمایشی'}).locator('.delete-note').click();
  await page.waitForFunction(()=>document.querySelectorAll('.saved-note').length===1);
  await page.reload();await page.locator('.saved-note').waitFor();assert.equal(await page.locator('.saved-note').count(),1);
  assert.match(await page.locator('.saved-note p').textContent(),/یادداشت دوم ویرایش شده/);
  await page.getByRole('button',{name:'تبدیل تاریخ',exact:true}).click();
  await page.locator('#convert-year').selectOption('1405');await page.locator('#convert-month').selectOption('6');await page.locator('#convert-day').selectOption('21');await page.locator('#convert-form button').click();
  assert.match(await page.locator('#convert-result').textContent(),/2026-09-12/);
  assert.equal(await page.locator('#convert-panel input').count(),0);
  await page.locator('#convert-year').selectOption('1403');await page.locator('#convert-month').selectOption('12');await page.locator('#convert-day').selectOption('30');
  await page.locator('#convert-year').selectOption('1404');assert.equal(await page.locator('#convert-day option').count(),29);assert.equal(await page.locator('#convert-day').inputValue(),'29');
  await page.locator('#calendar-type').selectOption('gregorian');await page.locator('#convert-year').selectOption('2024');await page.locator('#convert-month').selectOption('2');assert.equal(await page.locator('#convert-day option').count(),29);
  await page.locator('#convert-year').selectOption('2025');assert.equal(await page.locator('#convert-day option').count(),28);
  await page.locator('#convert-year').selectOption('2099');await page.locator('#convert-month').selectOption('1');await page.locator('#convert-day').selectOption('1');await page.locator('#convert-form button').click();await page.locator('#go-converted').click();
  assert.equal(await page.locator('.saved-note').count(),0);
  await page.locator('#remind-toggle').check();await page.locator('#note').fill('قرار آزمایشی');await page.locator('#note-form button[type=submit]').click();
  await page.locator('.saved-note[data-kind=reminder]').waitFor();
  assert.match(await page.locator('.saved-note[data-kind=reminder] .created-time').textContent(),/^ثبت [۰-۹]{2}:[۰-۹]{2}$/);
  assert.equal(await page.locator('#alert-count').isVisible(),false);
  const selectedBeforeAlerts=await page.locator('#selected-title').textContent();
  await page.locator('#note').fill('پیش‌نویس محفوظ بماند');
  await page.locator('#open-alerts').click();assert.equal(await page.locator('#all-reminders .reminder').count(),0);
  assert.equal(await page.locator('#home-screen').isVisible(),false);
  assert.equal(await page.getByRole('tab').count(),2);
  await page.locator('[data-reminder-filter=upcoming]').click();assert.equal(await page.locator('#all-reminders .reminder').count(),1);
  assert.equal(await page.locator('#alert-count').isVisible(),false);
  await page.locator('#back-home').click();
  assert.equal(await page.locator('#selected-title').textContent(),selectedBeforeAlerts);
  assert.equal(await page.locator('#note').inputValue(),'پیش‌نویس محفوظ بماند');
  await page.locator('#note-form button[type=submit]').click();await page.getByText('ذخیره شد',{exact:true}).waitFor();
  await page.locator('.saved-note[data-kind=note] .delete-note').click();await page.waitForFunction(()=>!document.querySelector('.saved-note[data-kind=note]'));
  const alarms=await worker.evaluate(()=>chrome.alarms.getAll());assert.equal(alarms.length,1);
  assert.equal((await worker.evaluate(()=>chrome.sidePanel.getPanelBehavior())).openPanelOnActionClick,true);
  const delivery=await page.evaluate(async()=>{
    const all=await chrome.storage.local.get(null),key=Object.keys(all).find(k=>k.startsWith('reminder:'));
    await chrome.storage.local.set({[key]:{...all[key],when:Date.now()-1000}});
    const result=await chrome.runtime.sendMessage({type:'sync'});
    return {result,firedAt:(await chrome.storage.local.get(key))[key].firedAt};
  });
  assert.equal(delivery.result.ok,true);assert.ok(delivery.firedAt);
  await page.waitForFunction(()=>!document.querySelector('#alert-count').hidden);
  assert.equal(await page.locator('#alert-count').textContent(),'۱');
  await page.locator('#open-alerts').click();await page.waitForFunction(()=>document.querySelector('#alert-count').hidden);
  assert.equal(await page.locator('#all-reminders .reminder').count(),1);
  await page.locator('[data-reminder-filter=upcoming]').click();assert.equal(await page.locator('#all-reminders .reminder').count(),0);
  await page.reload();await page.waitForFunction(()=>document.querySelector('#today-weekday').textContent.length>0);
  assert.equal(await page.locator('#alert-count').isVisible(),false);
  await page.locator('#open-alerts').click();await page.locator('#all-reminders .delete').click();await page.waitForFunction(()=>!document.querySelector('#all-reminders .reminder'));
  await page.screenshot({path:path.join(root,'screenshots','notifications.png'),fullPage:true});
  await page.locator('#back-home').click();
  assert.equal((await worker.evaluate(()=>chrome.alarms.getAll())).length,0);
  await page.locator('#today').click();await page.locator('.saved-note .delete-note').click();await page.waitForFunction(()=>document.querySelectorAll('.saved-note').length===0);
  assert.equal(await page.locator('.day.selected .note-dot').count(),0);
  await page.locator('#message').waitFor({state:'hidden'});
  await mkdir(path.join(root,'screenshots'),{recursive:true});
  await page.screenshot({path:path.join(root,'screenshots','month.png'),fullPage:true});
  await page.locator('#week-toggle').click();
  await page.screenshot({path:path.join(root,'screenshots','sidepanel.png'),fullPage:true});
  await page.setViewportSize({width:300,height:850});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.equal(await page.locator('#calendar .day').count(),7);
  await page.screenshot({path:path.join(root,'screenshots','compact-week.png'),fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS: real MV3 extension load, side panel action behavior, font, date conversion, invalid date, note persistence, reminder storage + alarm + real notification API + deletion, weekly view, 300px overflow, no page errors.');
}finally{await context?.close();await rm(profile,{recursive:true,force:true});}
